### ISSUE TITLE
Cannot resolve 'mdi-clock'

### ISSUE THREAD

**Issue by dragonsKnight5** [kordamp/ikonli#154]
Hi,
I'm trying to use a timepicker in my project but I keep hitting the following error
Cannot resolve 'mdi-clock'

below is the error trace log

```

java.lang.UnsupportedOperationException: Cannot resolve 'mdi-clock'
	at org.kordamp.ikonli.AbstractIkonResolver.resolve(AbstractIkonResolver.java:61)
	at org.kordamp.ikonli.javafx.IkonResolver.resolve(IkonResolver.java:73)
	at org.kordamp.ikonli.javafx.FontIconConverter.convert(FontIconConverter.java:50)
	at org.kordamp.ikonli.javafx.FontIconConverter.convert(FontIconConverter.java:28)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.calculateValue(CssStyleHelper.java:1628)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.lookup(CssStyleHelper.java:1192)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:858)
	at javafx.graphics@18.0.1/javafx.scene.Node.doProcessCSS(Node.java:9595)
	at javafx.graphics@18.0.1/javafx.scene.Node$1.doProcessCSS(Node.java:481)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:193)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@18.0.1/javafx.scene.control.Control.doProcessCSS(Control.java:902)
	at javafx.controls@18.0.1/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@18.0.1/javafx.scene.control.Control.doProcessCSS(Control.java:902)
	at javafx.controls@18.0.1/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSSImpl(ControlHelper.java:63)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.superProcessCSS(ControlHelper.java:55)
	at javafx.controls@18.0.1/javafx.scene.control.Control.doProcessCSS(Control.java:902)
	at javafx.controls@18.0.1/javafx.scene.control.Control$1.doProcessCSS(Control.java:89)
	at javafx.controls@18.0.1/com.sun.javafx.scene.control.ControlHelper.processCSSImpl(ControlHelper.java:67)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Parent.doProcessCSS(Parent.java:1400)
	at javafx.graphics@18.0.1/javafx.scene.Parent$1.doProcessCSS(Parent.java:125)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.ParentHelper.processCSSImpl(ParentHelper.java:98)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9477)
	at javafx.graphics@18.0.1/javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.graphics@18.0.1/javafx.scene.Scene.preferredSize(Scene.java:1770)
	at javafx.graphics@18.0.1/javafx.scene.Scene$2.preferredSize(Scene.java:396)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.SceneHelper.preferredSize(SceneHelper.java:66)
	at javafx.graphics@18.0.1/javafx.stage.Window$12.invalidated(Window.java:1163)
	at javafx.base@18.0.1/javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.base@18.0.1/javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:145)
	at javafx.graphics@18.0.1/javafx.stage.Window.setShowing(Window.java:1239)
	at javafx.graphics@18.0.1/javafx.stage.Window.show(Window.java:1254)
	at javafx.graphics@18.0.1/javafx.stage.Stage.show(Stage.java:277)
	at itp_central.ITP_Central.start(ITP_Central.java:34)
	at javafx.graphics@18.0.1/com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$9(LauncherImpl.java:847)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.lambda$runAndWait$12(PlatformImpl.java:484)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$10(PlatformImpl.java:457)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18.0.1/com.sun.javafx.application.PlatformImpl.lambda$runLater$11(PlatformImpl.java:456)
	at javafx.graphics@18.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
Exception in thread "JavaFX Application Thread" java.lang.UnsupportedOperationException: Cannot resolve 'mdi-clock'
	at org.kordamp.ikonli.AbstractIkonResolver.resolve(AbstractIkonResolver.java:61)
	at org.kordamp.ikonli.javafx.IkonResolver.resolve(IkonResolver.java:73)
	at org.kordamp.ikonli.javafx.FontIconConverter.convert(FontIconConverter.java:50)
	at org.kordamp.ikonli.javafx.FontIconConverter.convert(FontIconConverter.java:28)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.calculateValue(CssStyleHelper.java:1628)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.lookup(CssStyleHelper.java:1192)
	at javafx.graphics@18.0.1/javafx.scene.CssStyleHelper.transitionToState(CssStyleHelper.java:858)
	at javafx.graphics@18.0.1/javafx.scene.Node.doProcessCSS(Node.java:9595)
	at javafx.graphics@18.0.1/javafx.scene.Node$1.doProcessCSS(Node.java:481)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSSImpl(NodeHelper.java:193)
	at javafx.graphics@18.0.1/com.sun.javafx.scene.NodeHelper.processCSS(NodeHelper.java:146)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9477)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Node.processCSS(Node.java:9470)
	at javafx.graphics@18.0.1/javafx.scene.Scene.doCSSPass(Scene.java:572)
	at javafx.graphics@18.0.1/javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2494)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.Toolkit.lambda$runPulse$2(Toolkit.java:405)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:404)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:434)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:575)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:555)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.pulseFromQueue(QuantumToolkit.java:548)
	at javafx.graphics@18.0.1/com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$11(QuantumToolkit.java:352)
	at javafx.graphics@18.0.1/com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:96)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at javafx.graphics@18.0.1/com.sun.glass.ui.gtk.GtkApplication.lambda$runLoop$11(GtkApplication.java:316)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

the error appears to be related to AbstractIkonResolver but I can't find any mention of a mdi-clock component anywhere

any assistance resolving this would be greatly appreciated

**Comment by dragonsKnight5** [comment]
Never mind, another library I was using was using this one but didn't list which pack it was using.
ended up being material design pack in the end
